name: Build, Release and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: cache gradle packages
        uses: actions/cache@v4.2.0
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: setup jdk 8.0
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8.0
      - name: Build
        run: |-
          chmod +x gradlew
          ./gradlew javadoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: javadoc
          FOLDER: colonel-common/build/docs/javadoc
  build-and-release:
    name: Build, Release and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: cache gradle packages
        uses: actions/cache@v4.2.0
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: setup jdk 8.0
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8.0
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build project
        id: build_publish
        continue-on-error: true
        run: ./gradlew buildAndPublish
        env:
          IREPO_USERNAME: ${{ secrets.IREPO_USERNAME }}
          IREPO_PASSWORD: ${{ secrets.IREPO_PASSWORD }}
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            colonel-*/build/libs/
            colonel-common/build/docs/javadoc/
      - name: Get Project Info
        id: get_info
        run: |
          output=$(./gradlew properties)
          version=$(echo "$output" | grep "^version:" | awk '{print $2}')
          name=$(echo "$output" | grep "^name:" | awk '{print $2}')
          echo "project_version=$version" >> "$GITHUB_OUTPUT"
          echo "project_name=$name" >> "$GITHUB_OUTPUT"
          echo "Release Tag: $version"
          echo "Release Name: $name $version"
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_info.outputs.project_version }}
          release_name: ${{ steps.get_info.outputs.project_name }} ${{ steps.get_info.outputs.project_version }}
          draft: false
          prerelease: false
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.get_info.outputs.project_version }} colonel-*/build/libs/*.jar
